# Generated by Django 4.2.8 on 2024-04-01 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="movie_images/"),
                ),
                ("description", models.TextField(max_length=800)),
                ("release_date", models.DateField()),
                ("actors", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("trailer_link", models.URLField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
