# Generated by Django 4.2.8 on 2024-04-01 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("final_app", "0003_alter_movie_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="final_app.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        choices=[
                            (0.0, "0.0"),
                            (0.5, "0.5"),
                            (1.0, "1.0"),
                            (1.5, "1.5"),
                            (2.0, "2.0"),
                            (2.5, "2.5"),
                            (3.0, "3.0"),
                            (3.5, "3.5"),
                            (4.0, "4.0"),
                            (4.5, "4.5"),
                            (5.0, "5.0"),
                            (5.5, "5.5"),
                            (6.0, "6.0"),
                            (6.5, "6.5"),
                            (7.0, "7.0"),
                            (7.5, "7.5"),
                            (8.0, "8.0"),
                            (8.5, "8.5"),
                            (9.0, "9.0"),
                            (9.5, "9.5"),
                            (10.0, "10.0"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="final_app.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
