# Generated by Django 4.2.11 on 2024-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("final_app", "0007_remove_rating_review_text_rating_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="updated_at",
        ),
    ]
