# Generated by Django 4.2.8 on 2024-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_app", "0009_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
