# Generated by Django 4.2.11 on 2024-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_app", "0011_category_alter_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
