# Generated by Django 4.2.11 on 2024-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_app", "0012_alter_movie_category_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
        ),
    ]
